

development:
  adapter: postgresql
  encoding: utf8
  database: garagem_development
  username: postgres
  password: postgres
  pool: 5 # not mandatory
  timeout: 5000 # not mandatory
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: garagem_test
  username: postgres
  password: postgres
  pool: 5 # not mandatory
  timeout: 5000 # not mandatory
  host: localhost
  port: 5432

