# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccb152d6a61530769c581395562d6f04275320c50b5df0323eb9c02b3c6ef8fb16005fc59d9f4030f4edc6dcac5a1646c9cbd06a5947dc8ac4b9d438e897105b

test:
  secret_key_base: da0066fba93edc52f2ca313af05f27bc959ea86af8a0797da80620a345e5414dba40a191e265b43f3303bae9c5be494a42a6169dc703be95f1090da674ee8228

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
